"""Contains street suffix abbreviations."""

AU_Unit_CODES = {

'ANT':'Antenna',
'APT':'Apartment',
'ATM':'Automated Teller Machine',
'BBQ':'Barbecue',
'BTSD':'Boatshed',
'BLDG':'Building',
'BNGW':'Bungalow',
'CAGE':'Cage',
'CARP':'Carpark',
'CARS':'Carspace',
'CLUB':'Club',
'COOL':'Coolroom',
'CTGE':'Cottage',
'DUPL':'Duplex',
'FCTY':'Factory',
'FLAT':'Flat',
'GRGE':'Garage',
'HALL':'Hall',
'HSE':'House',
'KSK':'Kiosk',
'LSE':'Lease',
'LBBY':'Lobby',
'LOFT':'Loft',
'LOT':'Lot',
'MSNT':'Maisonette',
'MBTH':'Marine Berth',
'OFFC':'Office',
'RESV':'Reserve',
'ROOM':'Room',
'SHED':'Shed',
'SHOP':'Shop',
'SHRM':'Showroom',
'SIGN':'Sign',
'SITE':'Site',
'STLL':'Stall',
'STOR':'Store',
'STR':'Strata unit',
'STU':'Studio/studio apartment',
'SUBS':'Substation',
'SE':'Suite',
'TNCY':'Tenancy',
'TWR':'Tower',
'TNHS':'Townhouse',
'UNIT':'Unit',
'VLT':'Vault',
'VLLA':'Villa',
'WARD':'Ward',
'WHSE':'Warehouse',
'WKSH':'Workshop',
'U':'Unit'
}


AU_LEVEL_CODES = {

'B':'Basement',
'FL':'Floor',
'G':'Ground',
'L':'Level',
'LG':'Lower ground floor',
'M':'Mezzanine',
'OD':'Observation deck',
'P':'Parking',
'PTHS':'Penthouse',
'PLF':'Platform',
'PDM':'Podium',
'RT':'Rooftop',
'SB':'Sub-basement',
'UG':'Upper ground floor',

}


AU_STRRET_CODES = {
'ACCS':'Access',
'ALLY':'Alley',
'ALWY':'Alleyway',
'AMBL':'Amble',
'APP':'Approach',
'ARC':'Arcade',
'ARTL':'Arterial',
'ARTY':'Artery',
'AV':'Avenue',
'BA':'Banan',
'BEND':'Bend',
'BWLK':'Boardwalk',
'BVD':'Boulevard',
'BR':'Brace',
'BRAE':'Brae',
'BRK':'Break',
'BROW':'Brow',
'BYPA':'Bypass',
'BYWY':'Byway',
'CSWY':'Causeway',
'CTR':'Centre',
'CH':'Chase',
'CIR':'Circle',
'CCT':'Circuit',
'CRCS':'Circus',
'CL':'Close',
'CON':'Concourse',
'CPS':'Copse',
'CNR':'Corner',
'CT':'Court',
'CTYD':'Courtyard',
'COVE':'Cove',
'CR':'Crescent',
'CRST':'Crest',
'CRSS':'Cross',
'CSAC':'Cul-de-sac',
'CUTT':'Cutting',
'DALE':'Dale',
'DIP':'Dip',
'DR':'Drive',
'DVWY':'Driveway',
'EDGE':'Edge',
'ELB':'Elbow',
'END':'End',
'ENT':'Entrance',
'ESP':'Esplanade',
'EXP':'Expressway',
'FAWY':'Fairway',
'FOLW':'Follow',
'FTWY':'Footway',
'FORM':'Formation',
'FWY':'Freeway',
'FRTG':'Frontage',
'GAP':'Gap',
'GDNS':'Gardens',
'GTE':'Gate',
'GLDE':'Glade',
'GLEN':'Glen',
'GRA':'Grange',
'GRN':'Green',
'GR':'Grove',
'HTS':'Heights',
'HIRD':'Highroad',
'HWY':'Highway',
'HILL':'Hill',
'INTG':'Interchange',
'JNC':'Junction',
'KEY':'Key',
'LANE':'Lane',
'LNWY':'Laneway',
'LINE':'Line',
'LINK':'Link',
'LKT':'Lookout',
'LOOP':'Loop',
'MALL':'Mall',
'MNDR':'Meander',
'MEWS':'Mews',
'MTWY':'Motorway',
'NOOK':'Nook',
'OTLK':'Outlook',
'PDE':'Parade',
'PWY':'Parkway',
'PASS':'Pass',
'PSGE':'Passage',
'PATH':'Path',
'PWAY':'Pathway',
'PIAZ':'Piazza',
'PLZA':'Plaza',
'PKT':'Pocket',
'PNT':'Point',
'PORT':'Port',
'PROM':'Promenade',
'QDRT':'Quadrant',
'QYS':'Quays',
'RMBL':'Ramble',
'REST':'Rest',
'RTT':'Retreat',
'RDGE':'Ridge',
'RISE':'Rise',
'RD':'Road',
'RTY':'Rotary',
'RTE':'Route',
'ROW':'Row',
'RUE':'Rue',
'SVWY':'Serviceway',
'SHUN':'Shunt',
'SPUR':'Spur',
'SQ':'Square',
'ST':'Street',
'SBWY':'Subway',
'TARN':'Tarn',
'TCE':'Terrace',
'THFR':'Thoroughfare',
'TLWY':'Tollway',
'TOP':'Top',
'TOR':'Tor',
'TRK':'Track',
'TRL':'Trail',
'TURN':'Turn',
'UPAS':'Underpass',
'VALE':'Vale',
'VIAD':'Viaduct',
'VIEW':'View',
'VSTA':'Vista',
'WALK':'Walk',
'WKWY':'Walkway',
'WHRF':'Wharf',
'WYND':'Wynd',
}

AU_ROAD_SUFFIX_CODES = {

'CN':'Central',
'E':'East',
'EX':'Extension',
'LR':'Lower',
'N':'North',
'NE':'North East',
'NW':'North West',
'S':'South',
'SE':'South East',
'SW':'South West',
'UP':'Upper',
'W':'West',
}

AU_STATES_CODES ={
'NSW':'New South Wales',
'VIC':'Victoria',
'QLD':'Queensland',
'SA':'South Australia',
'WA':'Western Australia',
'TAS':'Tasmania',
'NT':'Northern Territory',
'ACT':'Australian Capital Territory',
'AAT':'Australian Antarctic Territory',
}


